name: Music Jonnor
favicon: null
layout_spectrum: 0.2829323075711727
typography_spectrum: 0.23568122391588986
title: Those who dance are considered insane by those who cannot hear the music
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#D8CAA8'
    - '#5C832F'
    - '#284907'
    - '#382513'
    - '#363942'
  brandStrength: 0.24395671067759395
  lightness: 0.3438056968152523
  saturation: 0.7049682552460581
  rhythmicContrast: 0.45225348975509405
purpose: []
