name: Music Jonnor
favicon: null
layout_spectrum: 0.9624980138614774
typography_spectrum: 0.931284217396751
title: Those who dance are considered insane by those who cannot hear the music
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  brandStrength: 0.1424816008657217
  lightness: 0.014002270763739944
  saturation: 0.32054692949168384
  rhythmicContrast: 0.3649632374290377
purpose: []
