name: Music Jonnor
favicon: null
layout_spectrum: 0.14525704341940582
typography_spectrum: 0.9515400719828904
title: Those who dance are considered insane by those who cannot hear the music
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#16193B'
    - '#35478C'
    - '#4E7AC7'
    - '#7FB2F0'
    - '#ADD5F7'
  brandStrength: 0.2716386504471302
  lightness: 0.8762311702594161
  saturation: 0.3340124459937215
  rhythmicContrast: 0.2544677935075015
purpose: []
