layout_spectrum: 0.1100760290864855
typography_spectrum: 0.5750418975949287
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.7754950076341629
  lightness: 0.10186492395587265
  saturation: 0.6124321094248444
  rhythmicContrast: 0.08246384910307825
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: Music Jonnor
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: 'Music, dark & hard'
description: Those who dance are considered insane by those who cannot hear the music
purpose: []
