name: jonnor-music
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5
title: Those who dance are considered insane by those who cannot hear the music
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.0625
  lightness: 0.0625
  saturation: 0.8125
  rhythmicContrast: 0.25
purpose: []
