typography_spectrum: 0.7869499723892659
color:
  brandColors:
    - '#DC3522'
    - '#D9CB9E'
    - '#374140'
    - '#2A2C2B'
    - '#1E1E20'
  brandStrength: 0.7724839753936976
  lightness: 0.9623188760597259
  saturation: 0.6760823903605342
  rhythmicContrast: 0.8278851322829723
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.81698
analytics:
  google: null
  facebook: null
  twitter: null
name: jonnor-music
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Those who dance are considered insane by those who cannot hear the music
purpose: []
