typography_spectrum: 0.5
color:
  brandColors:
    - '#ffffff'
    - '#bebebe'
    - '#1c1c1c'
    - '#797979'
    - '#bdb831'
  brandStrength: 0.0625
  lightness: 0.0625
  saturation: 0.8125
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.81698
analytics:
  google: null
  facebook: null
  twitter: null
name: jonnor-music
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Those who dance are considered insane by those who cannot hear the music
purpose: []
