name: Music Jonnor
favicon: null
layout_spectrum: 0.7205308482516557
typography_spectrum: 0.2343155776616186
title: Those who dance are considered insane by those who cannot hear the music
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#DC3522'
    - '#D9CB9E'
    - '#374140'
    - '#2A2C2B'
    - '#1E1E20'
  brandStrength: 0.7724839753936976
  lightness: 0.25
  saturation: 0.6760823903605342
  rhythmicContrast: 0.8278851322829723
purpose: []
